<div id="mobile-navi">
    <ul id="mobile-navi-tabs" class="tabs hidden-lg visible-md visible-md visible-sm visible-xs hidden-print">
        <li class="mobile-navi-item selected"><a href="$base$/">Home</a></li>
        <li class="mobile-navi-item"><a href="$base$/_index">All</a></li>
        <li class="mobile-navi-item"><a href="$base$/_categories">Categories</a></li>
        <li class="mobile-navi-item"><a href="$base$/_random">Random</a></li>
        <li class="mobile-navi-item"><a href="$base$/_activity">Recent</a></li>
    </ul>
</div>