
<li><a href="$base$/">Front page</a></li>
<li><a href="$base$/_index">All pages</a></li>
<li><a href="$base$/_categories">Categories</a></li>
<li><a href="$base$/_random">Random page</a></li>
<li><a href="$base$/_activity">Recent activity</a></li>
$if(wikiupload)$
    <li><a href="$base$/_upload">Upload a file</a></li>
$endif$
$if(feed)$
<li><a href="$base$/_feed/" type="application/atom+xml" rel="alternate" title="ATOM Feed">Atom feed</a></li>
$endif$
<li><a href="$base$/Help">Help</a></li>