<li  class="hide"><a href="$base$/">Home</a></li>
<li><a href="$base$/_index" title="All pages">All</a></li>
<li><a href="$base$/_categories">Categories</a></li>
<li><a href="$base$/_random" title="Random page">Random</a></li>
<li><a href="$base$/_activity" title="Recent activity">Recent</a></li>
$if(wikiupload)$
    <li><a href="$base$/_upload" title="Upload  a file">Upload</a></li>
$endif$
$if(feed)$
<li><a href="$base$/_feed/" type="application/atom+xml" rel="alternate" title="ATOM Feed">Atom feed</a></li>
$endif$
<li  class="hide"><a href="$base$/Help">Help</a></li>